### ISSUE TITLE
Question about car model 

### ISSUE THREAD

**Issue by didibaba** [mellocolate/carla-display-frontend#8]
Have you tried to use `export const CAR = {
  mesh: load('./assets/car.obj', OBJLoader),
  origin: [1.3, 0, 0],
  scale: 0.0009,
  color: [180, 180, 200]
};
` to load the car model? The attribution 'color' seems always to be black.

**Comment by wx9698** [comment]
No, I didn't. 
Did you use it before? @GilgameshD

**Comment by GilgameshD** [comment]
I tried to use .obj file for the car model, but I failed. I am not familiar with JS, maybe there is something wrong with the dependencies.
